IzvorniKod/RaiderLeague/RaiderLeague/Controllers/AccountPageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace RaiderLeague.Controllers
{
    public class AccountPageController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

IzvorniKod/RaiderLeague/RaiderLeague/Controllers/EditProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace RaiderLeague.Controllers
{
    public class EditProfileController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

IzvorniKod/RaiderLeague/RaiderLeague/Controllers/LoggedInController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace RaiderLeague.Controllers
{
    public class LoggedInController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult UploadBattleLog()
        {
            return View();
        }
    }
}

IzvorniKod/RaiderLeague/RaiderLeague/Controllers/UploadBattleLogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using RaiderLeague.Models;

namespace RaiderLeague.Controllers
{
    public class UploadBattleLogController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        String y = null;




        [HttpPost]
        public ActionResult Uploaded(BattleLogUpload model)
        {
            /*
            if (ModelState.IsValid)
            {
                BattleLog x = new BattleLog(model.battleLogUpload);
                if (x.getResult().Count < 2)
                {
                    ViewData["dps"] = "Invalid input!";
                }
                else
                {
                    ViewData["tps"] = "TPS= "+x.getResult().ElementAt(0);
                    ViewData["dps"] = "DPS= "+x.getResult().ElementAt(1);
                    ViewData["hps"] = "HPS= "+x.getResult().ElementAt(2);
                }
            }*/
            
            return View();
        }       
    }
}

IzvorniKod/RaiderLeague/RaiderLeague/Views/LoggedIn/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

@{
    Layout = "~/Views/Shared/_LayoutLoggedIn.cshtml";

}
<h2>Raider League</h2>

<input type ="button" value=" Upload your battle log" onclick="location.href='@Url.Action("Index", "UploadBattleLog")'" />

<input type="button" value=" Leaderboard" onclick="location.href='@Url.Action("LoggedIn", "Leaderboard")'" />

<input type="button" value=" Check your account page" onclick="location.href='@Url.Action("Index", "AccountPage")'" />

<input type="button" value=" Edit Profile" onclick="location.href='@Url.Action("Index", "EditProfile")'" />

IzvorniKod/RaiderLeague/RaiderLeague/Views/LoggedIn/UploadBattleLog.cshtml
@{
    ViewData["Title"] = "UploadBattleLog";
}

<h2>UploadBattleLog</h2>